


* X

X is a sonification plugin for Chimera. It uses Open Sound Control to communicate with SuperCollider. It is written in Python and needs pyOSC and SimpleOSC to communicate with SuperCollider. In SuperCollider, the Ambisonics Toolkit is used to spatialise the sounds.

If you have any comments or encounter problems with the installation instructions below, please let me know at [[mailto:holger.ballweg@northumbria.ac.uk]].

* Prerequisites
- SuperCollider 3.7 or later
  https://supercollider.github.io/
  - If using OpenSuSE, you can install it from [[https://software.opensuse.org/download.html?project=multimedia%253Aapps&package=supercollider][multimedia:apps]]
- UCSF Chimera 1.1 or later
  https://www.cgl.ucsf.edu/chimera/download.html

* Additional things to install

** For SuperCollider:
***  Ambisonics Toolkit (ATK)

Follow the instructions on:
http://www.ambisonictoolkit.net/download/supercollider/

Also install the kernels as described in:
http://www.ambisonictoolkit.net/download/kernels/

- The kernels should unpack to a directory called "kernels" with a subfolder called "FOA"
  - if not, rename the folder including "FOA" to just "kernels", otherwise ATK won't find it

You don't need the ATK Sound File Recordings.

* Testing the setup
** In SuperCollider
- Open test.scd
  - Evaluate the first block (Linux: Press =Ctrl+Enter=. Mac: =Cmd+Enter=)

* Running X
- Open SuperCollider and open the provided setup.scd file
  - Evaluate the whole file (Linux: Press =Ctrl+Enter=. Mac: =Cmd+Enter=)
- Open Chimera
  - Open IDLE (Tools->General Control->IDLE)
  - With the focus on IDLE, open X.py
  - Press F5 to run the code


